//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.209
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.0.3705.209.
// 
namespace WindowsApplication1.ptsgps_spsdev01 {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
	using System.Configuration;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SearchSoap", Namespace="urn:PTelecom/Intranet/SearchService")]
    public class Search : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        public IdentityCredentials IdentityCredentialsValue;
        
        /// <remarks/>
        public Search() {
            this.Url = ConfigurationManager.AppSettings["WebServiceSearchURL"];
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("IdentityCredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:PTelecom/Intranet/SearchService/getProperties", RequestNamespace="urn:PTelecom/Intranet/SearchService", ResponseNamespace="urn:PTelecom/Intranet/SearchService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetPropertiesResponse getProperties() {
            var results = this.Invoke("getProperties", new object[0]);
            return ((GetPropertiesResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetProperties(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getProperties", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public GetPropertiesResponse EndgetProperties(System.IAsyncResult asyncResult) {
            var results = this.EndInvoke(asyncResult);
            return ((GetPropertiesResponse)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("IdentityCredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:PTelecom/Intranet/SearchService/search", RequestNamespace="urn:PTelecom/Intranet/SearchService", ResponseNamespace="urn:PTelecom/Intranet/SearchService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SearchResponse search(string PropertyFilter, string FreeTextFilter, string OrderBy, int PageNumber, int PageSize) {
            var results = this.Invoke("search", new object[] {
                        PropertyFilter,
                        FreeTextFilter,
                        OrderBy,
                        PageNumber,
                        PageSize});
            return ((SearchResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginsearch(string PropertyFilter, string FreeTextFilter, string OrderBy, int PageNumber, int PageSize, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("search", new object[] {
                        PropertyFilter,
                        FreeTextFilter,
                        OrderBy,
                        PageNumber,
                        PageSize}, callback, asyncState);
        }
        
        /// <remarks/>
        public SearchResponse Endsearch(System.IAsyncResult asyncResult) {
            var results = this.EndInvoke(asyncResult);
            return ((SearchResponse)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:PTelecom/Intranet/SearchService")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:PTelecom/Intranet/SearchService", IsNullable=false)]
    public class IdentityCredentials : SoapHeader {
        
        /// <remarks/>
        public string IdentityName;
        
        /// <remarks/>
        public string IdentityPassword;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:PTelecom/Intranet/SearchService")]
    public class Item {
        
        /// <remarks/>
        public string Link;
        
        /// <remarks/>
        public int Size;
        
        /// <remarks/>
        public string Filename;
        
        /// <remarks/>
        public string CreationDate;
        
        /// <remarks/>
        public string ModifiedDate;
        
        /// <remarks/>
        public string Title;
        
        /// <remarks/>
        public string Author;
        
        /// <remarks/>
        public string Description;
        
        /// <remarks/>
        public string Keywords;
        
        /// <remarks/>
        public string Categories;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:PTelecom/Intranet/SearchService")]
    public class SearchResponse {
        
        /// <remarks/>
        public Item[] List;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int TotalHits;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalHitsSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int RangeMin;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RangeMinSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int RangeMax;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RangeMaxSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:PTelecom/Intranet/SearchService")]
    public class Property {
        
        /// <remarks/>
        public string Caption;
        
        /// <remarks/>
        public string FieldName;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:PTelecom/Intranet/SearchService")]
    public class GetPropertiesResponse {
        
        /// <remarks/>
        public Property[] Properties;
    }
}
