//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.209
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.0.3705.209.
// 
namespace WindowsApplication1.ptsgps_spsdev011 {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
	using System.Configuration;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UserMngSoap", Namespace="urn:PTelecom/Intranet/UserMngService")]
    public class UserMng : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        public IdentityCredentials IdentityCredentialsValue;
        
        public UserCredentials UserCredentialsValue;
        
        /// <remarks/>
        public UserMng() {
            this.Url = ConfigurationManager.AppSettings["WebServiceADSearchURL"];
			//"http://ptsgps-spsdev01/WebServices/usermng.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UserCredentialsValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("IdentityCredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:PTelecom/Intranet/UserMngService/batchRequest", RequestNamespace="urn:oasis:names:tc:DSML:2:0:core", ResponseElementName="batchResponse", ResponseNamespace="urn:oasis:names:tc:DSML:2:0:core", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("modifyResponse", typeof(modifyResponse))]
        [return: System.Xml.Serialization.XmlElementAttribute("searchResponse", typeof(searchResponse))]
        [return: System.Xml.Serialization.XmlElementAttribute("errorResponse", typeof(errorResponse))]
        [return: System.Xml.Serialization.XmlElementAttribute("addResponse", typeof(addResponse))]
        [return: System.Xml.Serialization.XmlElementAttribute("delResponse", typeof(delResponse))]
        public object[] batchRequest([System.Xml.Serialization.XmlElementAttribute("modifyRequest", typeof(modifyRequest))] [System.Xml.Serialization.XmlElementAttribute("addRequest", typeof(addRequest))] [System.Xml.Serialization.XmlElementAttribute("delRequest", typeof(delRequest))] [System.Xml.Serialization.XmlElementAttribute("searchRequest", typeof(searchRequest))] object[] Items) {
            var results = this.Invoke("batchRequest", new object[] {
                        Items});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginbatchRequest(object[] Items, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("batchRequest", new object[] {
                        Items}, callback, asyncState);
        }
        
        /// <remarks/>
        public object[] EndbatchRequest(System.IAsyncResult asyncResult) {
            var results = this.EndInvoke(asyncResult);
            return ((object[])(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:PTelecom/Intranet/UserMngService")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:PTelecom/Intranet/UserMngService", IsNullable=false)]
    public class UserCredentials : SoapHeader {
        
        /// <remarks/>
        public string Domain;
        
        /// <remarks/>
        public string Username;
        
        /// <remarks/>
        public string Password;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public class delResponse {
        
        /// <remarks/>
        public string errorMessage;
        
        /// <remarks/>
        public string referral;
        
        /// <remarks/>
        public ResultCode resultCode;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public class ResultCode {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int code;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codeSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string descr;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public class addResponse {
        
        /// <remarks/>
        public string errorMessage;
        
        /// <remarks/>
        public string referral;
        
        /// <remarks/>
        public ResultCode resultCode;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public class errorResponse {
        
        /// <remarks/>
        public string message;
        
        /// <remarks/>
        public string detail;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public class SearchResultDone {
        
        /// <remarks/>
        public ResultCode resultcode;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public class searchResultEntry {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attr")]
        public attr[] attr;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dn;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public class attr {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("value")]
        public string[] value;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public class searchResponse {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("searchResultReference", typeof(string[]))]
        [System.Xml.Serialization.XmlElementAttribute("searchResultEntry", typeof(searchResultEntry))]
        public object[] Items;
        
        /// <remarks/>
        public SearchResultDone searchResultDone;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public class modifyResponse {
        
        /// <remarks/>
        public string errorMessage;
        
        /// <remarks/>
        public string referral;
        
        /// <remarks/>
        public ResultCode resultCode;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public class attribute {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public class searchRequest {
        
        /// <remarks/>
        public string filter;
        
        /// <remarks/>
        public attribute[] attributes;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dn;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string scope;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string derefAliases;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int sizeLimit;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sizeLimitSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int timeLimit;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timeLimitSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool typesOnly;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typesOnlySpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public class delRequest {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dn;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public class addRequest {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attr")]
        public attr[] attr;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dn;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public class Modification {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("value")]
        public string[] value;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string operation;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:DSML:2:0:core")]
    public class modifyRequest {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("modification")]
        public Modification[] modification;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dn;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:PTelecom/Intranet/UserMngService")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:PTelecom/Intranet/UserMngService", IsNullable=false)]
    public class IdentityCredentials : SoapHeader {
        
        /// <remarks/>
        public string IdentityName;
        
        /// <remarks/>
        public string IdentityPassword;
    }
}
